name: Allure Report с публикацией

on:
  schedule:
    - cron: '0 9 * * *'      # Каждый день в 9:00 UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v4

      - name: Установка Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Разрешить права на gradlew
        run: chmod +x ./gradlew

      - name: Запуск тестов
        run: ./gradlew clean test --no-daemon -Dselenide.headless=true

      - name: Установка Allure CLI
        run: |
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.22.1/allure-commandline-2.22.1.zip
          unzip allure-commandline-2.22.1.zip -d allure-cli
          echo "ALLURE=$PWD/allure-cli/bin/allure" >> $GITHUB_ENV

      - name: Генерация Allure-отчёта
        run: |
          $ALLURE generate build/allure-results -o allure-report --clean

      - name: Публикация на GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: allure-report/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          commit_message: "Обновление Allure-отчёта"