name: Autotest

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Run tests
        run: ./gradlew clean test

      - name: Install Allure
        if: always()
        run: |
          sudo apt-get install -y wget unzip
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.37.0/allure-commandline-2.37.0.zip
          unzip allure-commandline-2.37.0.zip
          sudo mv allure-2.37.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate allure report
        if: always()
        run: allure generate build/allure-results --clean -o build/allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/allure-report


