name: Autotest

on:
  push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Run tests
        run: ./gradlew clean test

      - name: Save allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path:
            allure-results

  generate-report:
    if: always()
    runs-on: ubuntu-latest
    needs: test
    name: Generate Report
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.37.0/allure-2.37.0.tgz && sudo tar -zxvf allure-2.37.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.37.0/bin/allure /usr/bin/allure
      - name: Download all workflow artifact
        uses: actions/download-artifact@v4
      - run: allure generate -c allure-results -o _site
      - name: Store generated report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site


  publish-report:
    if: always()
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication
    steps:
      - name: Download all workflow artifact
        uses: actions/download-artifact@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  send-report:
    runs-on: ubuntu-latest
    needs: generate-report
    if: always()
    name: Send Report by Email
    steps:
      - name: Download report
        uses: actions/download-artifact@v4
        with:
          name: _site
          path: _site

      - name: Archive report
        run: |
          zip -r allure-report.zip _site/

      - name: –û—Ç–ø—Ä–∞–≤–∏—Ç—å –≤ Telegram
        uses: appleboy/telegram-action@v1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
              **–†–µ–∑—É–ª—å—Ç–∞—Ç –ø—Ä–æ–≥–æ–Ω–∞ —Ç–µ—Å—Ç–æ–≤**
              
              üîó [–ü–æ—Å–º–æ—Ç—Ä–µ—Ç—å –æ—Ç—á—ë—Ç](https://marinahoruzhaya.github.io/test_jenkins/)

          format: markdown



